name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKERFILE_PATH: ./server/dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          file: ${{ env.DOCKERFILE_PATH }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
